name: Run Python script periodically

on:
  schedule:
    # Toutes les 15 minutes de 9h00 à 23h59
    - cron: '0,15,30,45 9-23 * * *'
    - cron: '59 23 * * *'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      # Étape 3 : Cache des dépendances pip et Playwright
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-deps-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: |
          if [ ! -d ~/.cache/ms-playwright ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            playwright install chromium
            playwright install-deps
          fi

      # Étape 5 : Installer et démarrer Xvfb
      - name: Install and start Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &

      # Étape 6 : Générer automatiquement le fichier .env
      - name: Create .env file
        run: |
          cat > .env << EOL
          user=${{ secrets.USER }}
          password=${{ secrets.PASSWORD }}
          host=${{ secrets.HOST }}
          dbname=${{ secrets.DBNAME }}
          port=${{ secrets.PORT }}
          DIGIFOOD_EMAIL=${{ secrets.DIGIFOOD_EMAIL }}
          DIGIFOOD_PASSWORD=${{ secrets.DIGIFOOD_PASSWORD }}
          EOL

      # Étape 7 : Exécuter le script Python
      - name: Run script
        run: |
          python script.py
        env:
          DISPLAY: :99