name: Run Python script periodically

on:
  schedule:
    # Chaque heure pile de 7h00 à 23h00
    - cron: '0 8 * * *'
    - cron: '0 9 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
    - cron: '0 20 * * *'
    - cron: '0 21 * * *'
    - cron: '0 22 * * *'
    - cron: '0 23 * * *'
    
    # Chaque demi-heure de 7h30 à 23h30
    - cron: '30 11 * * *'
    - cron: '30 12 * * *'
    - cron: '30 13 * * *'
    - cron: '30 14 * * *'
    - cron: '30 15 * * *'
    - cron: '30 16 * * *'
    - cron: '30 17 * * *'
    - cron: '30 18 * * *'
    - cron: '30 19 * * *'
    - cron: '30 20 * * *'
    - cron: '30 21 * * *'
    - cron: '30 22 * * *'
    - cron: '30 23 * * *'

    # À 23h59
    - cron: '59 23 * * *'

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Étape 3 : Cache des dépendances pip
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Étape 4 : Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium
          playwright install-deps

      # Étape 5 : Installer et démarrer Xvfb
      - name: Install and start Xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &

      # Étape 6 : Générer automatiquement le fichier .env
      - name: Create .env file
        run: |
          cat > .env << EOL
          user=${{ secrets.USER }}
          password=${{ secrets.PASSWORD }}
          host=${{ secrets.HOST }}
          dbname=${{ secrets.DBNAME }}
          port=${{ secrets.PORT }}
          DIGIFOOD_EMAIL=${{ secrets.DIGIFOOD_EMAIL }}
          DIGIFOOD_PASSWORD=${{ secrets.DIGIFOOD_PASSWORD }}
          EOL

      # Étape 7 : Exécuter le script Python
      - name: Run script
        run: |
          python script.py
        env:
          DISPLAY: :99